-- ============================================================
-- Seed-Daten: 480 Schüler:innen der KRS Schriesheim (Schuljahr 2025/26)
-- Auto-generiert aus Musterlösung Schüler 2025-2026.csv
-- Codes zufällig, Format: <KLASSE>-XXXX (Alphabet ohne I,O,0,1)
-- ============================================================

INSERT INTO schueler (code, vorname, nachname, klasse, klassenstufe) VALUES
  ('6B-TPBK', 'Mohammed', 'Abdulsamad', '6b', 6),
  ('9B-AAMF', 'Justus', 'Ackermann', '9b', 9),
  ('7A-H6RD', 'Miriam', 'Adam', '7a', 7),
  ('7D-S88X', 'Semilore Pelumi', 'Adekunle', '7d', 7),
  ('8D-VAXZ', 'Enes', 'Ademoski', '8d', 8),
  ('7C-4SLJ', 'Aleksandra', 'Aderek', '7c', 7),
  ('9C-V93F', 'Gülbin', 'Akacak', '9c', 9),
  ('8A-M9ET', 'Brian Vincent', 'Akhigbe', '8a', 8),
  ('10B-VQEW', 'Dennis', 'Aktekin', '10b', 10),
  ('7C-VQDG', 'Tom', 'Albrecht', '7c', 7),
  ('8B-C34G', 'Zoe Luzia', 'Albrecht', '8b', 8),
  ('6A-J222', 'Abdulrahman', 'Aldaoud Alhfel', '6a', 6),
  ('5C-G8RT', 'Ali', 'Alhaj Ahmad', '5c', 5),
  ('6B-NY6S', 'Dominik', 'Ali', '6b', 6),
  ('6A-DG5E', 'Mohammad Naim', 'Alimi', '6a', 6),
  ('8C-2K8T', 'Hesham', 'Alkhiyami', '8c', 8),
  ('6A-HCDM', 'Ali', 'Alkurdiyeh', '6a', 6),
  ('5A-UYZB', 'Naya', 'Almeli', '5a', 5),
  ('5C-YMLQ', 'Youssif', 'Alragheb', '5c', 5),
  ('7D-6GPJ', 'Athena', 'Amini', '7d', 7),
  ('9D-AZC9', 'Ghazal', 'Amini', '9d', 9),
  ('8B-RYWW', 'Noel', 'Andreas', '8b', 8),
  ('9A-YBJU', 'Lara Stefanie', 'Andrew', '9a', 9),
  ('7B-CXPA', 'Theodor Julius', 'Arndt', '7b', 7),
  ('10C-PJ5J', 'Tooba Tul Noor', 'Asghar', '10c', 10),
  ('10B-RND4', 'Endrit', 'Asllani', '10b', 10),
  ('9A-795Q', 'Mia', 'Avdimetaj', '9a', 9),
  ('10A-NTRF', 'Colin Klaus Teddy', 'Bähr', '10a', 10),
  ('7B-SGZ4', 'Leopold Michael', 'Bähr', '7b', 7),
  ('8D-XRFW', 'Berken', 'Barcin', '8d', 8),
  ('10C-UFE5', 'Philipp', 'Barczak', '10c', 10),
  ('10B-QAHD', 'Sophia', 'Barisic', '10b', 10),
  ('9A-FXDY', 'Lucien Kenji', 'Barth', '9a', 9),
  ('6A-9TKQ', 'Adele Lea Soley', 'Bartling', '6a', 6),
  ('10C-4D8Z', 'Adam', 'Barzizoui', '10c', 10),
  ('6A-FJGR', 'Zakaria', 'Barzizoui', '6a', 6),
  ('5C-D8AT', 'Lukas', 'Batke', '5c', 5),
  ('5A-28UK', 'Charlotte', 'Bauer', '5a', 5),
  ('9A-ZLFK', 'Chiara Soraya Mina', 'Bauer', '9a', 9),
  ('10B-UHKZ', 'Elif', 'Bayraktar', '10b', 10),
  ('6C-GWAH', 'Arda Linus', 'Becht', '6c', 6),
  ('9D-3H4Y', 'Angelina-Monique', 'Beck', '9d', 9),
  ('7C-3LW5', 'Hannah', 'Becker', '7c', 7),
  ('5A-Q2U8', 'Paul', 'Bedu-Addo', '5a', 5),
  ('8B-WMYY', 'Jana', 'Behm', '8b', 8),
  ('8A-4PST', 'Selina', 'Behrens', '8a', 8),
  ('6C-MYE5', 'Finn Louis', 'Behringer', '6c', 6),
  ('7A-7VU4', 'Tamina Fiona Sophie', 'Behringer', '7a', 7),
  ('8D-DXZJ', 'Shoeb', 'Ben Glail', '8d', 8),
  ('6A-KCTY', 'Darwin Jakob', 'Bender', '6a', 6),
  ('8D-QAVS', 'Nidal Sam', 'Benlarbi', '8d', 8),
  ('6C-VVN4', 'Anna Magdalena Zoë', 'Berger', '6c', 6),
  ('8B-Z44E', 'Luisa Marie', 'Bernd', '8b', 8),
  ('9A-QLEE', 'Mounia', 'Beslem', '9a', 9),
  ('5A-QM89', 'Laura', 'Betz', '5a', 5),
  ('9A-5P6Y', 'Isabell Sofie', 'Biel', '9a', 9),
  ('5B-FCU2', 'Leonie', 'Bischoff', '5b', 5),
  ('9A-VQFT', 'Nele Sarah', 'Bläker', '9a', 9),
  ('10C-RK2L', 'Naja-Chiara', 'Bleck', '10c', 10),
  ('5B-3F8J', 'Dariyan', 'Bletsch', '5b', 5),
  ('9C-PTEQ', 'Maximilian Carl', 'Blim', '9c', 9),
  ('10B-BQLC', 'Melina Sandrine', 'Blüml', '10b', 10),
  ('6B-ZWBF', 'Luca', 'Bocazio', '6b', 6),
  ('8A-FMJS', 'Massimo Samuel', 'Bocazio', '8a', 8),
  ('6A-QB6A', 'Paul', 'Bodrozic-Selak', '6a', 6),
  ('9B-P8YY', 'Paula', 'Boese', '9b', 9),
  ('5A-953D', 'Nadia', 'Bogucka-Dabek', '5a', 5),
  ('10A-MUBA', 'Luis', 'Böhler', '10a', 10),
  ('5C-PXP6', 'Anas', 'Bousfiha', '5c', 5),
  ('5C-5K5L', 'Elleni', 'Bozuric', '5c', 5),
  ('9A-3S85', 'Mina-Aurelia', 'Bozuric', '9a', 9),
  ('5B-56Z5', 'Julian', 'Brand', '5b', 5),
  ('9A-VQ8N', 'Lina', 'Brand', '9a', 9),
  ('8D-7DJ4', 'Leonie', 'Braun', '8d', 8),
  ('10C-6U3J', 'Noah Silas', 'Braun', '10c', 10),
  ('6C-UKKE', 'Lotta Marie', 'Breinig', '6c', 6),
  ('6C-9KYM', 'Eliah Oh-Yoon', 'Breit', '6c', 6),
  ('6A-VGT8', 'Mirza', 'Brkic', '6a', 6),
  ('8D-WG9B', 'Mikita', 'Buhai', '8d', 8),
  ('5A-LV7L', 'Luis', 'Burgi', '5a', 5),
  ('8D-EPQU', 'Imhan', 'Butt', '8d', 8),
  ('9D-J6ER', 'Maximilian', 'Bzdok', '9d', 9),
  ('7A-RZHP', 'Maja Luise', 'Camin', '7a', 7),
  ('10A-2H46', 'Enya', 'Caruso', '10a', 10),
  ('9A-B6GP', 'Henry', 'Casuccio', '9a', 9),
  ('9B-L8ED', 'Zara', 'Cátić', '9b', 9),
  ('8D-R985', 'Marlon David', 'Chepkoech', '8d', 8),
  ('VKL-9D2N', 'Tanisha', 'Chhabra', 'VKL', NULL),
  ('8C-QMMZ', 'Sebastian Michael Friedrich', 'Chmelik', '8c', 8),
  ('6B-B8E7', 'Nikola Emilia', 'Chodyniecka', '6b', 6),
  ('8B-DGAJ', 'Malina', 'Cooman', '8b', 8),
  ('7A-SFZD', 'Hailey Celine', 'Crawford', '7a', 7),
  ('10B-U453', 'Antonia', 'Cuturic', '10b', 10),
  ('10C-3ZMJ', 'Christiana', 'Cvitkovic', '10c', 10),
  ('6B-L45D', 'Cristiano', 'Cvitkovic', '6b', 6),
  ('8D-A8KL', 'Wanesa', 'Dabek', '8d', 8),
  ('5C-JE2G', 'Josephine', 'Dähmel', '5c', 5),
  ('5A-HHGF', 'Noah', 'Dähmel', '5a', 5),
  ('9B-ZBVY', 'Davor', 'Dakovic', '9b', 9),
  ('5C-V9YL', 'Lejla', 'Dalipovic', '5c', 5),
  ('6C-WXUC', 'Roman Ludwig', 'Dammert', '6c', 6),
  ('9B-XZMR', 'Santino', 'DeGeorge', '9b', 9),
  ('9C-AEPY', 'Josephine Annemarie Valentina', 'Denfeld', '9c', 9),
  ('5B-LSWA', 'Stella Daniela Renee', 'Denfeld', '5b', 5),
  ('10A-VE6F', 'Erik', 'Dewor', '10a', 10),
  ('9C-R2J6', 'Luis Enrique', 'Diaz Torres', '9c', 9),
  ('5A-B4K4', 'Johann', 'Ding', '5a', 5),
  ('8C-JSBU', 'Valentina Sophie', 'Dinkel', '8c', 8),
  ('9C-XXRZ', 'Aaron', 'Döbele', '9c', 9),
  ('6B-3GP3', 'Luca', 'Döbele', '6b', 6),
  ('9B-MQ54', 'Masal Deniz', 'Döner', '9b', 9),
  ('8C-MT9A', 'Nena-Sarina', 'Döring', '8c', 8),
  ('9C-HZQH', 'Lennard', 'Driest', '9c', 9),
  ('8D-8RSQ', 'Milijam', 'Drljic', '8d', 8),
  ('7B-SEEG', 'Ante', 'Dugandzic', '7b', 7),
  ('7B-XQZE', 'Matea', 'Dugandzic', '7b', 7),
  ('8A-5LMF', 'Theo', 'Eberhardt', '8a', 8),
  ('10C-PY7G', 'Julius Titus', 'Ebert', '10c', 10),
  ('5C-TQ95', 'Vincent Emilius', 'Ebert', '5c', 5),
  ('8B-5ULU', 'Henri', 'Eggers', '8b', 8),
  ('7B-36K8', 'Mohammed Riad', 'El Omari', '7b', 7),
  ('8A-GHUW', 'Mariam', 'El Ouarti', '8a', 8),
  ('5A-56E6', 'Mohamed', 'El Ouarti', '5a', 5),
  ('9C-D4D7', 'Malek Michael', 'El Rhazzouly', '9c', 9),
  ('9B-7E6C', 'Djamila', 'Elbah', '9b', 9),
  ('9C-Q9BU', 'Nasreddine', 'Elbah', '9c', 9),
  ('5A-2K7R', 'Nael', 'Ender', '5a', 5),
  ('9C-G2WW', 'Eleah Theresa', 'Englert', '9c', 9),
  ('8B-EW48', 'Parham', 'Eskandari', '8b', 8),
  ('9D-5S7P', 'Anne-Marie', 'Eva', '9d', 9),
  ('5C-3R5W', 'Paul', 'Eva', '5c', 5),
  ('6C-8V69', 'Axel', 'Ewald', '6c', 6),
  ('9B-S2HQ', 'Charlene', 'Fernandez', '9b', 9),
  ('8A-X9TJ', 'Canel', 'Fidanci', '8a', 8),
  ('5B-Q3ZR', 'Emilio', 'Flößer', '5b', 5),
  ('5B-P5PU', 'Paul', 'Friedl', '5b', 5),
  ('6B-P23E', 'Julius', 'Fröhlich', '6b', 6),
  ('7C-CP62', 'Emilia Anette Lucilina', 'Frohn', '7c', 7),
  ('6C-E949', 'Emilie Melina Stefanie', 'Frosch', '6c', 6),
  ('5B-PTF3', 'Mia-Sophie', 'Frosch', '5b', 5),
  ('6A-QWBT', 'Ilias', 'Funk', '6a', 6),
  ('9C-C52J', 'Sara', 'Gallian', '9c', 9),
  ('6B-QRR6', 'Giuseppe Gabrielle', 'Gambino', '6b', 6),
  ('6C-PLNF', 'Jonida', 'Gashi', '6c', 6),
  ('5C-6BGT', 'Emilia Sophie', 'Gaßmann', '5c', 5),
  ('8D-Z9ZS', 'Merle-Emilian', 'Gayer', '8d', 8),
  ('8D-53HA', 'Michele-Emilio', 'Gayer', '8d', 8),
  ('8C-BHND', 'Malin', 'Geiger', '8c', 8),
  ('5B-3S2T', 'Kilian Levent', 'Gerlach', '5b', 5),
  ('6B-U8WQ', 'Paul Hermann', 'Gerstenberger', '6b', 6),
  ('6B-KH64', 'Ibrahim', 'Ghafouri', '6b', 6),
  ('8A-XE6V', 'Hossein', 'Ghasempour', '8a', 8),
  ('9B-CU5B', 'Flora', 'Gjigolli', '9b', 9),
  ('7B-TWM2', 'Leonie', 'Gnörich', '7b', 7),
  ('10B-JANB', 'Janne', 'Gommlich', '10b', 10),
  ('7C-3QES', 'Damian', 'Gönnheimer', '7c', 7),
  ('7B-N53J', 'Anna-Mia', 'Goss', '7b', 7),
  ('10A-SKC8', 'Philipp', 'Goss', '10a', 10),
  ('10C-23JZ', 'Yusuf', 'Gözen', '10c', 10),
  ('6B-NNGU', 'Samuel Ian', 'Gritsch', '6b', 6),
  ('7C-QUYT', 'Tayler', 'Grüber', '7c', 7),
  ('5C-Y6VY', 'Kuzey', 'Güldal', '5c', 5),
  ('8C-DLXK', 'Lilly Ella', 'Güllübag', '8c', 8),
  ('8B-2P76', 'Evin', 'Güngör', '8b', 8),
  ('9C-PVZB', 'Marie', 'Gutfleisch', '9c', 9),
  ('10B-UHK6', 'Samia Elise', 'Güzel', '10b', 10),
  ('7C-57AA', 'Loreen Monika', 'Haase', '7c', 7),
  ('6A-K9YV', 'Ivan', 'Hajduk', '6a', 6),
  ('6C-TV3Y', 'Elena', 'Haji Akbari', '6c', 6),
  ('9D-SAN3', 'Emely Carina', 'Hardt', '9d', 9),
  ('5B-UAN8', 'Constantin', 'Hartmann', '5b', 5),
  ('5A-B6EW', 'Jerome', 'Hartmann', '5a', 5),
  ('7C-HLP6', 'Vincent Stephan', 'Hartmann', '7c', 7),
  ('8D-SNHP', 'Yolien', 'Hartmann', '8d', 8),
  ('8B-JDCR', 'Greta Zoe', 'Hassel', '8b', 8),
  ('10B-B47G', 'Tristan', 'Hauck', '10b', 10),
  ('6B-6NKC', 'Ole', 'Häussler', '6b', 6),
  ('5C-T8PK', 'Marleen', 'Heberle', '5c', 5),
  ('7C-QKFA', 'Melina', 'Heberle', '7c', 7),
  ('5C-RJAU', 'Anna', 'Hedza', '5c', 5),
  ('7C-FKQR', 'Armin Alexander Victor', 'Heiderich', '7c', 7),
  ('10A-SLQ9', 'Lilith Carolin', 'Heinz', '10a', 10),
  ('6B-TMQL', 'Connor Markus', 'Heising', '6b', 6),
  ('5A-HQ2E', 'Anna', 'Helfert', '5a', 5),
  ('7A-RBLX', 'Yuji Alexander', 'Henzler', '7a', 7),
  ('7A-Q3EZ', 'Dean Nevio', 'Heringhaus', '7a', 7),
  ('9D-JY42', 'Lyonel Lamar', 'Hirsch', '9d', 9),
  ('7B-HX6X', 'Carla Lisa', 'Hohl', '7b', 7),
  ('9C-R4RK', 'Nils, David', 'Hohl', '9c', 9),
  ('8C-6VJR', 'Tayler Lunis', 'Höhnle', '8c', 8),
  ('7D-C5CG', 'David', 'Höhr', '7d', 7),
  ('5A-E9NB', 'Nick', 'Höhr', '5a', 5),
  ('8B-NUJL', 'Janis Alexander', 'Holdernig', '8b', 8),
  ('10C-2KEY', 'Felix Stefan', 'Huben', '10c', 10),
  ('5B-56F3', 'Luke Carl', 'Huben', '5b', 5),
  ('6A-YHJQ', 'Gabriel', 'Huljak', '6a', 6),
  ('5B-J6F6', 'Luka', 'Huljak-Pavisic', '5b', 5),
  ('9C-RB8L', 'Sophia Anna', 'Hummel', '9c', 9),
  ('8B-MBD5', 'Lea Sophie', 'Hünniger', '8b', 8),
  ('7C-ZDMU', 'Lion', 'Hutwagner', '7c', 7),
  ('8D-YG3G', 'Ema', 'Ibrahimi', '8d', 8),
  ('7B-Z7DB', 'Lina-Alexa', 'Ibrahim-Mahmoud', '7b', 7),
  ('10A-YLWF', 'Sabrina', 'Idt', '10a', 10),
  ('5C-LZNU', 'Charlie', 'Imerlishvili', '5c', 5),
  ('7A-XFVP', 'Nicolas', 'Imerlishvili', '7a', 7),
  ('8A-ZVHX', 'Mara Amélie', 'Innocente', '8a', 8),
  ('8D-XG48', 'Sunita', 'Iseni', '8d', 8),
  ('9B-UYLQ', 'Cassidy', 'Isifeh', '9b', 9),
  ('10A-BHNE', 'Louis', 'Jakob', '10a', 10),
  ('6B-ZZP5', 'Amir Ali', 'Jamali', '6b', 6),
  ('9B-SNWL', 'Laila', 'Jandula', '9b', 9),
  ('7A-K753', 'Romy Nina', 'John', '7a', 7),
  ('9D-4ZY3', 'Tobias Alexander', 'John', '9d', 9),
  ('8D-6K46', 'Julian', 'Jórczyk', '8d', 8),
  ('10B-RHA3', 'Fabian', 'Kairies', '10b', 10),
  ('7A-6PC3', 'Mehrsa', 'Kalaki', '7a', 7),
  ('ZUGANG-F2EL', 'Max', 'Kalpin', 'Zugang', NULL),
  ('10C-ETXE', 'Tom Erik', 'Kämmerer', '10c', 10),
  ('7D-LTH9', 'Lajla', 'Karanovic', '7d', 7),
  ('10A-2UV2', 'Ali Eren', 'Karasu', '10a', 10),
  ('6B-2F4L', 'Erdal', 'Karavis', '6b', 6),
  ('7C-DU2G', 'Marjam', 'Kardava', '7c', 7),
  ('6C-GC3G', 'Amina', 'Kasmi', '6c', 6),
  ('10A-69DE', 'Michel', 'Käßner', '10a', 10),
  ('7B-WB3H', 'Felix', 'Kellner', '7b', 7),
  ('10C-XUR8', 'Franziska Elle', 'Kempf', '10c', 10),
  ('8C-2K4B', 'Katharina', 'Kempf', '8c', 8),
  ('9D-R6DS', 'Frederic Leon', 'Kerner', '9d', 9),
  ('10C-DABR', 'Leon', 'Kertik', '10c', 10),
  ('8B-797L', 'Ihsanullah', 'Khairi', '8b', 8),
  ('5C-A6KN', 'Humam', 'Khaled', '5c', 5),
  ('7D-3XD8', 'Sara', 'Khaled', '7d', 7),
  ('6A-A4JJ', 'Bisenk Hira', 'Kirmizi', '6a', 6),
  ('6B-4ZSF', 'Jayson Kai', 'Kiss', '6b', 6),
  ('10B-DX62', 'Kaya Carolina', 'Klavehn', '10b', 10),
  ('8B-83PJ', 'Kian Constantin', 'Klavehn', '8b', 8),
  ('8B-MV86', 'Marie Elisabeth', 'Klinger', '8b', 8),
  ('7A-JDBT', 'Nikias', 'Klotz', '7a', 7),
  ('5B-QGEH', 'Silas', 'Klotz', '5b', 5),
  ('5A-EYAX', 'Haily Sophie', 'Knapp', '5a', 5),
  ('10A-YXFP', 'Vivienne', 'Knoll', '10a', 10),
  ('5B-ATAU', 'Josie', 'Kohm', '5b', 5),
  ('9B-XWXY', 'Sina Maria', 'Kolb', '9b', 9),
  ('6B-MBXF', 'Davyd', 'Kolombai', '6b', 6),
  ('5B-YLKZ', 'Ceylin', 'Kolubüyük', '5b', 5),
  ('7A-DF79', 'Celina', 'Köpcke', '7a', 7),
  ('7A-NRNM', 'Mailina', 'Kopetsch', '7a', 7),
  ('6C-TQFS', 'Mariia', 'Koreshkova', '6c', 6),
  ('7C-HVTE', 'Lara', 'Korkowski', '7c', 7),
  ('9A-FHRD', 'Timo', 'Korkowski', '9a', 9),
  ('7D-XHGK', 'Yelyzaveta', 'Kovalenko', '7d', 7),
  ('9B-LD27', 'András Károly', 'Krájnik', '9b', 9),
  ('7C-TSP2', 'Damon', 'Krambeer', '7c', 7),
  ('7A-WC5U', 'Felipè', 'Krämer', '7a', 7),
  ('9B-JTCW', 'Alisiia', 'Kravets', '9b', 9),
  ('7B-ED76', 'Noah', 'Kreis', '7b', 7),
  ('5B-35U5', 'Anna Liara', 'Kreische', '5b', 5),
  ('6C-DN2N', 'Melina', 'Krijezi', '6c', 6),
  ('8B-ZN4K', 'Amelie Rebecca', 'Krotsch', '8b', 8),
  ('5B-3YGJ', 'Karol Filip', 'Kuessner-Rychlewski', '5b', 5),
  ('6A-X637', 'Mika', 'Kunkel', '6a', 6),
  ('5A-3MAW', 'Niko', 'Kunkel', '5a', 5),
  ('8C-36XW', 'Savas', 'Küplü', '8c', 8),
  ('10C-Q3ZS', 'Jessica-Alicia', 'Kurz', '10c', 10),
  ('7D-Z2H9', 'Ivan', 'Kushnirenko', '7d', 7),
  ('7C-D3RD', 'Jan', 'Kusow', '7c', 7),
  ('5B-69TR', 'Amely', 'Lang', '5b', 5),
  ('5A-YZTN', 'Paul', 'Langer', '5a', 5),
  ('7C-U7LC', 'Henry Hugo', 'Large', '7c', 7),
  ('8A-D3B6', 'Paul', 'Lassak', '8a', 8),
  ('9B-3R8E', 'Fabiana', 'Laun', '9b', 9),
  ('6A-5HAC', 'Kim', 'Lehmann', '6a', 6),
  ('9D-QNM5', 'Mia', 'Lehmann', '9d', 9),
  ('7B-MM8X', 'Marlene', 'Lohse', '7b', 7),
  ('9C-N9ES', 'Noah Eliah', 'Lopez', '9c', 9),
  ('10B-LTET', 'Christopher', 'Lörsch', '10b', 10),
  ('5B-HBDL', 'Patricia', 'Lozancic', '5b', 5),
  ('9A-TB8Z', 'Isabel', 'Lukic', '9a', 9),
  ('8B-FPDN', 'Alessia Kalea', 'Lunzer', '8b', 8),
  ('7D-37W4', 'Samantha Andrea', 'Maaß', '7d', 7),
  ('5A-KEFJ', 'Haymen', 'Mahamed Jamal', '5a', 5),
  ('7C-JA77', 'Alen', 'Malinovic', '7c', 7),
  ('10A-YAFM', 'Merlin', 'Manske', '10a', 10),
  ('8B-C3DR', 'Mathilda', 'Markart', '8b', 8),
  ('7A-T57F', 'Milan', 'Marzai', '7a', 7),
  ('9A-QNLS', 'Sina', 'Marzai', '9a', 9),
  ('10B-A4ZP', 'Savannah Avery Bell', 'Mattes', '10b', 10),
  ('7C-9DH8', 'Helene Karina', 'Mayer', '7c', 7),
  ('5A-CSWY', 'Emma', 'Meisel', '5a', 5),
  ('8C-HXSF', 'Flora Sofia', 'Mendes Leitao', '8c', 8),
  ('6A-45CV', 'Berkin', 'Menekseli', '6a', 6),
  ('9C-WG64', 'Rojin', 'Menekseli', '9c', 9),
  ('10C-Z47P', 'Linus', 'Merz', '10c', 10),
  ('8C-9482', 'Leon Alexander', 'Michel', '8c', 8),
  ('9D-JSPM', 'Neda', 'Mir Amanollah', '9d', 9),
  ('8D-BYMG', 'Felicia Christin', 'Mirek', '8d', 8),
  ('9D-2RYH', 'Eva', 'Mitrev', '9d', 9),
  ('6C-F7D8', 'Luca Aaron', 'Mohr', '6c', 6),
  ('6A-MABW', 'Iban', 'Morad Hayder', '6a', 6),
  ('6B-EXA3', 'Sarah Luna', 'Mühldorfer', '6b', 6),
  ('8B-YLX6', 'Anesa', 'Mujkanovic', '8b', 8),
  ('9A-C7FJ', 'Leon', 'Münch', '9a', 9),
  ('9D-UBYW', 'Drin', 'Murati', '9d', 9),
  ('9A-HFUT', 'Fabian Frank Erhard', 'Nagel', '9a', 9),
  ('7A-U59H', 'Hannah Isa Kristina', 'Nagel', '7a', 7),
  ('9D-E4ZC', 'Prince Julyan', 'Nahrstedt', '9d', 9),
  ('5C-6MR6', 'Frederik', 'Nast', '5c', 5),
  ('ZUGANG-BTGR', 'Marie', 'Neff', 'Zugang', NULL),
  ('6C-ZGM9', 'Ayla', 'Noldes', '6c', 6),
  ('10B-LMTQ', 'Darian Noah', 'Nossratian', '10b', 10),
  ('8C-LW5B', 'Anna Emilia', 'Nowosad', '8c', 8),
  ('8D-9YET', 'Ann-Kathrin', 'Nunes Villing', '8d', 8),
  ('9D-LFR4', 'Lea Sophie', 'Obert', '9d', 9),
  ('8B-CBHF', 'Jannis', 'Oeldorf', '8b', 8),
  ('5A-V2Q7', 'Anna Matilda', 'Offermann', '5a', 5),
  ('8C-3D7D', 'Jonas Bennett', 'Olbert', '8c', 8),
  ('8C-6Q78', 'Salma', 'Omer', '8c', 8),
  ('8D-ZVXJ', 'Ladaynian', 'Onehidebawo', '8d', 8),
  ('ZUGANG 5ER-WCK7', 'Davut', 'Örnek', 'Zugang 5er', NULL),
  ('9B-QS4N', 'Ilayda', 'Özdemir', '9b', 9),
  ('8C-3NJV', 'Alea', 'Paloj', '8c', 8),
  ('8D-SJZ7', 'Angelos', 'Pantos', '8d', 8),
  ('8D-WWSJ', 'Kseniia', 'Parymska', '8d', 8),
  ('9D-TSYW', 'Lena', 'Pavic', '9d', 9),
  ('10A-XS2J', 'Natalie', 'Pavíc', '10a', 10),
  ('7A-ELP7', 'Alexander', 'Petereit', '7a', 7),
  ('8A-R8E3', 'Ksenia', 'Petrychenko', '8a', 8),
  ('9C-E5TJ', 'Cristiano', 'Pettineo', '9c', 9),
  ('6C-TNTS', 'Emely Evelyn', 'Pfanenstil', '6c', 6),
  ('9C-UE4E', 'Leon', 'Pfanenstil', '9c', 9),
  ('8C-YEUH', 'Emma', 'Pfeifer', '8c', 8),
  ('8A-S5BE', 'Lina', 'Pfeifer', '8a', 8),
  ('8A-Y9ZK', 'Nicos Leon', 'Pfeifer', '8a', 8),
  ('8C-UE4K', 'Rebecca Annett', 'Piecuch', '8c', 8),
  ('8C-XHW2', 'Mark', 'Pirozhenko', '8c', 8),
  ('10B-FNYQ', 'Maya', 'Plischke', '10b', 10),
  ('10B-EFK5', 'Stefanie Edeltraud', 'Pohl', '10b', 10),
  ('9B-WE8K', 'Nele Josephine', 'Probst', '9b', 9),
  ('7C-C673', 'Hannes Kevin', 'Pröll', '7c', 7),
  ('9C-9QQF', 'Maria Daniela', 'Pröll', '9c', 9),
  ('9D-4JTG', 'Jonas', 'Pschowski', '9d', 9),
  ('9D-SD5H', 'Niclas Joachim', 'Pschowski', '9d', 9),
  ('9B-M3NN', 'Albion', 'Qufaj', '9b', 9),
  ('5C-9BF7', 'Altin', 'Qufaj', '5c', 5),
  ('5A-NB7J', 'Valentin-Alexandru', 'Raileanu', '5a', 5),
  ('7C-2QRJ', 'Luis Henri', 'Rath', '7c', 7),
  ('8A-8LTH', 'Florian', 'Reber', '8a', 8),
  ('5A-2YJU', 'Emilie', 'Regula', '5a', 5),
  ('8C-YSCT', 'Johann-Sebastian Volker', 'Reibold', '8c', 8),
  ('8A-4ZZQ', 'Roksana', 'Reif', '8a', 8),
  ('8A-4CQ7', 'Anna Maria', 'Rein', '8a', 8),
  ('8A-LQLW', 'Bleona', 'Rexhepaj', '8a', 8),
  ('10C-94K8', 'Leyla', 'Rexhepaj', '10c', 10),
  ('7A-Y3PT', 'Hannes', 'Richert', '7a', 7),
  ('10C-AAQ8', 'Leon', 'Röger', '10c', 10),
  ('10B-TWT2', 'Tom', 'Röger', '10b', 10),
  ('6C-8PNH', 'Theo Anton', 'Roschig', '6c', 6),
  ('7A-HXC6', 'Malte Lars', 'Rufenach', '7a', 7),
  ('7B-B876', 'Khalid Ahmad', 'Sahaar', '7b', 7),
  ('9D-WZ8H', 'Lema', 'Sahaar', '9d', 9),
  ('8C-EEPP', 'Liam', 'Salbinger', '8c', 8),
  ('8A-CU2S', 'Svenja', 'Salja', '8a', 8),
  ('6C-Q95Y', 'Sophia', 'Sander', '6c', 6),
  ('10B-7387', 'Lara Marie', 'Saric', '10b', 10),
  ('8A-8QHC', 'Demian', 'Sasse Rojas', '8a', 8),
  ('9C-SFLJ', 'Mitja', 'Sator', '9c', 9),
  ('8C-EZJL', 'Zara', 'Sauer', '8c', 8),
  ('6A-8LUS', 'Jannis', 'Schäfer', '6a', 6),
  ('9A-AMXQ', 'Daliah', 'Scheuber', '9a', 9),
  ('9B-JXQ7', 'Victoria Sonja', 'Schlechter', '9b', 9),
  ('6B-JLB7', 'Luca Tino', 'Schlicksupp', '6b', 6),
  ('7A-XF7S', 'Rebekka Louise', 'Schmid', '7a', 7),
  ('9C-G8TU', 'Anna-Lena', 'Schmitt', '9c', 9),
  ('8C-EWGQ', 'Dilara Elisabeth Saray', 'Schmitt', '8c', 8),
  ('10B-DC8Z', 'Fabienne Sophie', 'Schmitt', '10b', 10),
  ('10B-77DG', 'Finn', 'Schmitt', '10b', 10),
  ('7B-38GK', 'Yolanda Sofia', 'Schmitt', '7b', 7),
  ('7B-A94F', 'Leo', 'Schneider', '7b', 7),
  ('10C-EZGF', 'Mika Sascha', 'Scholl', '10c', 10),
  ('7C-H53F', 'Maximilian', 'Schöner', '7c', 7),
  ('9B-94HV', 'Vanessa Marie', 'Schörnig', '9b', 9),
  ('8A-8SWP', 'Vincent', 'Schreck', '8a', 8),
  ('6B-5666', 'Silas', 'Schremser', '6b', 6),
  ('5A-D493', 'Finnya Marina Marita', 'Schreuder', '5a', 5),
  ('9A-CYXR', 'Lena', 'Schröder', '9a', 9),
  ('7B-E7SU', 'Philipp Michael Stefan', 'Schröder', '7b', 7),
  ('6C-2EPB', 'Emily Renée', 'Schulz', '6c', 6),
  ('8D-PUTD', 'Adrian Lucas', 'Schwarz', '8d', 8),
  ('10C-VXB6', 'Nia Sofie', 'Schwarz', '10c', 10),
  ('6C-XAF9', 'Frieda-Marie', 'Schweim', '6c', 6),
  ('5B-BBHH', 'Mika Noel', 'Sedivec', '5b', 5),
  ('ZUGANG 5ER-MUED', 'Etienne Rufus Levi', 'Selig', 'Zugang 5er', NULL),
  ('7B-FVLW', 'Aneta', 'Serhiichuk', '7b', 7),
  ('9C-95BX', 'Leona', 'Sertolli', '9c', 9),
  ('9D-NPLA', 'Elina', 'Seyrich', '9d', 9),
  ('5B-KUTT', 'Jicheol', 'Shin', '5b', 5),
  ('9C-7237', 'Kilian Stefan', 'Sieber', '9c', 9),
  ('7C-7W6P', 'Olivia', 'Siebig', '7c', 7),
  ('8A-Y5DF', 'Elin', 'Siegert', '8a', 8),
  ('6A-G58W', 'Ian', 'Siegert', '6a', 6),
  ('9B-5RS2', 'Harleen', 'Singh', '9b', 9),
  ('7D-LJPS', 'Yehor', 'Solohup', '7d', 7),
  ('8B-3HDG', 'Paula', 'Sommer', '8b', 8),
  ('7B-UBNK', 'Bastian Robin', 'Spies', '7b', 7),
  ('7A-G9S3', 'Justus Leonard', 'Stadler', '7a', 7),
  ('7A-7XWR', 'Klaus', 'Steinert', '7a', 7),
  ('10B-FZDE', 'Miriam', 'Stern', '10b', 10),
  ('7D-7DAU', 'Johanna Carolina', 'Stöhr', '7d', 7),
  ('9B-6B57', 'Marc', 'Stöhr', '9b', 9),
  ('8C-PR5S', 'Alexander', 'Stranz', '8c', 8),
  ('6B-FVJA', 'Fabian Torben', 'Strauß', '6b', 6),
  ('9B-PV6N', 'Philippa Seraphina Anastasia', 'Ströck', '9b', 9),
  ('8B-8Y7Y', 'Calista', 'Stuhlträger', '8b', 8),
  ('6B-Q2G3', 'Mohammad Reza', 'Sultani', '6b', 6),
  ('6A-EB73', 'Artur', 'Surmai', '6a', 6),
  ('7D-67K2', 'Hanna', 'Surmai', '7d', 7),
  ('5C-CLLB', 'Harun', 'Süzer', '5c', 5),
  ('6C-6WKY', 'Sophia Margarethe', 'Syrer', '6c', 6),
  ('10B-B6KN', 'Amira', 'Tahiri', '10b', 10),
  ('5A-JNQK', 'Jancher', 'Tamar', '5a', 5),
  ('6A-HTXP', 'Ayan-Attila', 'Tamas', '6a', 6),
  ('9A-RUV8', 'Fatma', 'Tamer', '9a', 9),
  ('5B-BLVE', 'Jana', 'Tamer', '5b', 5),
  ('9A-R3PE', 'Noran', 'Tamer', '9a', 9),
  ('5C-YEKD', 'Elif', 'Tapki', '5c', 5),
  ('8A-XW3L', 'Zilan', 'Tapki', '8a', 8),
  ('8A-Q6BX', 'Miran', 'Taycimen', '8a', 8),
  ('10C-P8UQ', 'Emilia', 'Teichmann', '10c', 10),
  ('5C-NXF9', 'Moritz', 'Telser Lorente', '5c', 5),
  ('10A-ARDQ', 'Paul', 'Telser Lorente', '10a', 10),
  ('7A-YDZP', 'Nico', 'Thomas', '7a', 7),
  ('9A-ZDGD', 'Albatrit', 'Tolaj', '9a', 9),
  ('10A-EJG4', 'Laura', 'Tomica', '10a', 10),
  ('10A-BD35', 'Yannis Robin', 'Tonn', '10a', 10),
  ('7A-375Q', 'Joy-Sophie', 'Ugiomoh', '7a', 7),
  ('9C-QSAE', 'Lena', 'Uhl', '9c', 9),
  ('5C-W4KU', 'Ben', 'Ullmer', '5c', 5),
  ('5A-PPUG', 'Frida', 'Ullrich', '5a', 5),
  ('6C-CMNJ', 'Leonie Felia', 'Unser', '6c', 6),
  ('5C-B5R9', 'Boglarka Piroska', 'Vago', '5c', 5),
  ('5B-CN6J', 'Elias', 'van der Steenhoven', '5b', 5),
  ('9B-UGT3', 'Emilia', 'Vanegas', '9b', 9),
  ('6A-EEJS', 'Julia', 'Velika', '6a', 6),
  ('5C-L9D5', 'Teja', 'Verksnyte', '5c', 5),
  ('5A-PSAC', 'Arblin', 'Vishi', '5a', 5),
  ('8A-MRQD', 'Kira', 'Vlasenko', '8a', 8),
  ('6A-FZ34', 'Fynn Levin', 'Volz', '6a', 6),
  ('9B-S6JX', 'Julia', 'von Westernhagen', '9b', 9),
  ('9D-6FYZ', 'Imanya Oriana', 'Wade', '9d', 9),
  ('5C-WH9C', 'Imilian Ozren', 'Wade', '5c', 5),
  ('8B-S883', 'Lina', 'Waldenmayr', '8b', 8),
  ('9C-6853', 'Lennart', 'Walenda', '9c', 9),
  ('9A-WLRN', 'Florine Rose', 'Walther', '9a', 9),
  ('10C-RXMK', 'Lars Ulrich', 'Weber', '10c', 10),
  ('5B-AQ79', 'Sophia', 'Weber', '5b', 5),
  ('7B-GASG', 'Till Norman', 'Weber', '7b', 7),
  ('10A-8Y57', 'Levin', 'Weichenberger', '10a', 10),
  ('10A-4JW7', 'Collin Bastian Alessandro', 'Weindorf', '10a', 10),
  ('7B-5QUN', 'Jamie-Noel', 'Weindorf', '7b', 7),
  ('6C-HZ3L', 'Jakob Elias Nikolai', 'Weissgärber', '6c', 6),
  ('9A-VSV2', 'Jonas Emauel', 'Weissgärber', '9a', 9),
  ('8B-FVA4', 'Fabio', 'Wenthe', '8b', 8),
  ('10A-MH99', 'Henri Leonard', 'Werner', '10a', 10),
  ('6B-DYNS', 'Emilie', 'Wesner', '6b', 6),
  ('7A-Y5E6', 'Cian Aron Loric', 'Wild', '7a', 7),
  ('9A-FZWA', 'Oskar', 'Willenberg', '9a', 9),
  ('7C-2336', 'Fabian Isaias', 'Wiltschka', '7c', 7),
  ('10A-CBBG', 'Tobias', 'Wiltschka', '10a', 10),
  ('7A-UM2P', 'Leonie', 'Wink', '7a', 7),
  ('10A-SYP8', 'Lisa-Emily', 'Witmann', '10a', 10),
  ('8B-8972', 'Niko', 'Witt', '8b', 8),
  ('10A-KHP6', 'Leon', 'Woche', '10a', 10),
  ('6C-6Q3Z', 'Joleen Mexine', 'Wolf', '6c', 6),
  ('9A-HPGW', 'Jonas', 'Wolf', '9a', 9),
  ('5B-CVR5', 'Paul Valantin', 'Wozniak', '5b', 5),
  ('8B-9JLS', 'Benjamin', 'Yaman', '8b', 8),
  ('7D-SX6G', 'Ecrin', 'Yildizalkan', '7d', 7),
  ('6A-L3D5', 'Mohamad', 'Yousef', '6a', 6),
  ('7B-7QBT', 'Lia', 'Zipperle', '7b', 7),
  ('9D-E46Y', 'Jana', 'Zitnjak', '9d', 9);
